Repository codeit-team9/give-more, pull requests merged in 2023-12, with the labels that each got.

#6 chore: update discussion template
  .github/DISCUSSION_TEMPLATE/Daily_Meeting.yml
Labels: 세팅

#8 프로젝트 세팅
  .eslintrc.json
  .github/pull-request-template.md
  .gitignore
  .husky/pre-commit
  .prettierrc
  README.md
  next.config.js
  package-lock.json
  package.json
  postcss.config.js
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.woff2
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Light.woff2
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.woff2
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.woff2
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Thin.woff2
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/fonts.css
  src/styles/reset.css
  tsconfig.json
Labels: 세팅, 1일

#18 eslint error: Delete ␍ prettier/prettier 에러 문제
  .eslintrc.json
Labels: fix, 세팅

#23 ESLint, Prettier 수정
  .eslintrc.json
  .gitignore
  .prettierrc
  package.json
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/css/fonts.css
  src/styles/css/reset.css
Labels: 세팅, 30분

#19 '로고 버튼' 클릭
  custom.d.ts
  next.config.js
  package-lock.json
  package.json
  src/assets/images/logo_icon.svg
  src/components/@common/LogoButton/LogoButton.tsx
  src/pages/jobLists.tsx
Labels: 30분, 컴포넌트

#16 컬러팔레트
  src/pages/_app.tsx
  src/styles/colors.css
Labels: 30분, 스타일

#27 GNB 메뉴 버튼
  src/components/@common/GNBMenuButton/GNBMenuButton.module.css
  src/components/@common/GNBMenuButton/GNBMenuButton.tsx
Labels: 30분, 컴포넌트

#32 feat: 임금 뱃지 구현
  src/components/notice/WageBadge/WageBadge.tsx
  src/components/notice/WageBadge/WageBadgeUI.module.css
  src/components/notice/WageBadge/WageBadgeUI.tsx
  src/pages/_app.tsx
  src/styles/css/colors.css
  src/utils/averageWage.ts
Labels: 컴포넌트, 3시간

#33 fix: font-size 62.5% 적용 안되는 문제 #28
  src/styles/css/fonts.css
Labels: fix

#34 Footer
  src/assets/images/envelop_icon.svg
  src/assets/images/facebook_icon.svg
  src/assets/images/instagram_icon.svg
  src/assets/images/search_icon.svg
  src/components/@common/Footer/Footer.module.css
  src/components/@common/Footer/Footer.tsx
  src/components/@common/SearchBar/SearchBar.module.css
  src/components/@common/SearchBar/SearchBar.tsx
Labels: 컴포넌트, 3시간

#42 Post Card 컴포넌트 구현
  src/assets/images/clock_icon-gray.svg
  src/assets/images/clock_icon.svg
  src/assets/images/path_icon-gray.svg
  src/assets/images/path_icon.svg
  src/components/notice/HourlyPayBadge/HourlyPayBadge.tsx
  src/components/notice/HourlyPayBadge/HourlyPayBadgeUI.module.css
  src/components/notice/HourlyPayBadge/HourlyPayBadgeUI.tsx
  src/components/notice/PostCard/PostCard.module.css
  src/components/notice/PostCard/PostCard.tsx
  src/components/notice/PostCard/PostCardDescription.module.css
  src/components/notice/PostCard/PostCardDescription.tsx
  src/components/notice/WageBadge/WageBadge.tsx
  src/components/notice/WageBadge/WageBadgeUI.tsx
  src/utils/averageHourlyPay.ts
  src/utils/averageWage.ts
  src/utils/getIconByType.ts
  src/utils/separatorHourlyPay.ts
Labels: 1일, 컴포넌트

#29 SearchBar
  src/components/@common/SearchBar/SearchBar.tsx
Labels: 컴포넌트, 1시간

#49 GNBNav
  src/components/@common/GNBMenuButton/GNBMenuButton.tsx
  src/components/@common/GNBNav/GNBNav.module.css
  src/components/@common/GNBNav/GNBNav.tsx
  src/components/@common/LogoButton/LogoButton.module.css
  src/components/@common/LogoButton/LogoButton.tsx
  src/components/@common/SearchBar/SearchBar.module.css
Labels: 컴포넌트, 6시간

#54 상세 필터 버튼 구현
  src/components/notice/DetailFilterButton/DetailFilterButton.module.css
  src/components/notice/DetailFilterButton/DetailFilterButton.tsx
Labels: 30분, 컴포넌트

#59 상태 승인/거절 버튼
  src/components/@common/StateButton/StateButton.module.css
  src/components/@common/StateButton/StateButton.tsx
  src/components/@common/UserTypeButton/UserTypeButton.module.css
  src/components/@common/UserTypeButton/UserTypeButton.tsx
  src/pages/index.tsx
Labels: 컴포넌트, 1시간

#65 readme
  README.md
Labels: 1시간

#50 맞춤 공고 화면
  src/@types/notice.types.ts
  src/components/notice/CustomizedNotice/CustomizedNotice.tsx
  src/components/notice/CustomizedNotice/CustomizedNoticeUI.module.css
  src/components/notice/CustomizedNotice/CustomizedNoticeUI.tsx
  src/components/notice/NoticeList/NoticeList.module.css
  src/components/notice/NoticeList/NoticeList.tsx
  src/components/notice/PostCard/PostCard.module.css
  src/components/notice/PostCard/PostCard.tsx
  src/utils/formatWorkTime.ts
Labels: 컴포넌트, 3시간

#67 Toast 구현
  src/components/@common/Toast/Toast.module.css
  src/components/@common/Toast/Toast.tsx
  src/constants/TOAST.ts
Labels: 컴포넌트, 6시간

#57 공통 버튼
  package-lock.json
  package.json
  src/components/@common/Button/InActiveButton.module.css
  src/components/@common/Button/InActiveButton.tsx
  src/components/@common/Button/LoginButton.module.css
  src/components/@common/Button/LoginButton.tsx
Labels: 컴포넌트, 1시간

#74 zustand 설치 및 로그인 여부 hook
  package-lock.json
  package.json
  src/components/@common/Button/InActiveButton.module.css
  src/components/@common/Button/InActiveButton.tsx
  src/components/@common/Button/LoginButton.module.css
  src/components/@common/Button/LoginButton.tsx
  src/components/@common/Input/Textarea.module.css
  src/components/@common/StateButton/StateButton.module.css
  src/components/@common/StateButton/StateButton.tsx
  src/components/@common/UserTypeButton/UserTypeButton.tsx
  src/hooks/useLoginInfo.tsx
  src/pages/index.tsx
Labels: 세팅, 기능

#69 회원 유형 버튼
  src/assets/images/blanked_icon.svg
  src/assets/images/checked_icon.svg
  src/assets/images/primary_icon.svg
  src/components/@common/UserTypeButton/CheckedIcon.tsx
  src/components/@common/UserTypeButton/UserTypeButton.module.css
  src/components/@common/UserTypeButton/UserTypeButton.tsx
Labels: 컴포넌트, 3시간

#78 Primary Button 추가, Logo 수정
  src/components/@common/Button/PrimaryButton.module.css
  src/components/@common/Button/PrimaryButton.tsx
  src/components/@common/Input/Input.module.css
  src/components/@common/LogoButton/LogoButton.module.css
  src/components/@common/LogoButton/LogoButton.tsx
Labels: fix, 컴포넌트
