Repository codeit-team9/give-more, pull requests merged in 2024-01, with the labels that each got.

#84 내 페이지 상세
  src/components/@common/Button/PrimaryButton.module.css
  src/components/@common/Footer/Footer.module.css
  src/components/@common/GNBMenuButton/GNBMenuButton.module.css
  src/components/@common/GNBNav/GNBNav.module.css
  src/components/@common/GNBNav/GNBNav.tsx
  src/components/@common/LogoButton/LogoButton.module.css
  src/components/@common/NotificationButton/NotificationButton.module.css
  src/components/@common/SearchBar/SearchBar.module.css
  src/pages/profile/index.tsx
  src/pages/profile/profile.module.css
  src/pages/profile/register.tsx
Labels: 페이지

#87 신청 타입 추가
  src/components/@common/Modal/Button.tsx
  src/components/@common/Modal/Modal/Modal.tsx
Labels: 30분, 컴포넌트

#93 Notification isActive 전역 상태 관리
  src/components/@common/GNBNav/GNBNav.tsx
  src/components/@common/NotificationButton/NotificationButton.tsx
  src/hooks/useNotification.tsx
  src/pages/profile/index.tsx
Labels: 기능

#100 페이지네이션, 전체 공고, 공고리스트 페이지 구현, 자잘한 수정
  next.config.js
  src/@types/notice.types.ts
  src/assets/images/arrow_left_gray_icon.svg
  src/assets/images/arrow_left_icon.svg
  src/assets/images/arrow_right_gray_icon.svg
  src/assets/images/arrow_right_icon.svg
  src/components/@common/DropDown/DropdownList.module.css
  src/components/@common/DropDown/DropdownUI.tsx
  src/components/@common/Footer/Footer.module.css
  src/components/@common/GNBMenuButton/GNBMenuButton.tsx
  src/components/@common/GNBNav/GNBNav.module.css
  src/components/@common/Input/DateInput.module.css
  src/components/@common/Modal/FilterModal/FilterAddress/FilterAddress.module.css
  src/components/@common/Modal/Wrapper.module.css
  src/components/@common/Modal/Wrapper.tsx
  src/components/@common/pagination/Pagination.module.css
  src/components/@common/pagination/Pagination.tsx
  src/components/notice/CustomizedNotice/CustomizedNotice.tsx
  src/components/notice/DetailFilterButton/DetailFilterButton.tsx
  src/components/notice/NoticeCard/NoticeCard.tsx
  src/components/notice/NoticeCard/NoticeCardDescription.tsx
  src/components/notice/NoticeCustomized/NoticeCustomized.tsx
  src/components/notice/NoticeCustomized/NoticeCustomizedUI.module.css
  src/components/notice/NoticeCustomized/NoticeCustomizedUI.tsx
  src/components/notice/NoticeEntire/NoticeEntire.module.css
  src/components/notice/NoticeEntire/NoticeEntire.tsx
  src/components/notice/NoticeList/NoticeList.tsx
  src/hooks/useFilter.ts
  src/hooks/usePagination.ts
  src/pages/NoticePage.module.css
  src/pages/index.tsx
Labels: 1일, 컴포넌트, 기능, 페이지

#102 내 프로필 등록 페이지
  src/components/@common/Button/PrimaryButton.module.css
  src/components/@common/DropDown/DropdownUI.module.css
  src/components/@common/Input/Input.tsx
  src/components/@common/Input/Textarea.module.css
  src/components/@common/Input/Textarea.tsx
  src/components/@common/Modal/Button.module.css
  src/hooks/useRegist.ts
  src/pages/my-profile/test.tsx
  src/pages/profile/detail.tsx
  src/pages/profile/index.tsx
  src/pages/profile/profile.module.css
  src/pages/profile/register.tsx
  src/pages/profile/registration.tsx
  src/pages/signin/index.tsx
Labels: 페이지

#107 로그인 회원가입 수정
  src/components/@common/Input/SetEmailInput.tsx
  src/components/@common/Input/SetPasswordInput.tsx
  src/components/@common/Toast/Toast.module.css
  src/components/@common/UserTypeButton/UserTypeButton.tsx
  src/hooks/useSignup.tsx
  src/pages/owner/index.tsx
  src/pages/signin/index.tsx
  src/pages/signin/signin.module.css
  src/pages/signup/index.tsx
  src/pages/signup/signup.module.css
Labels: 기능

#117 공고 상세 페이지 구현
  src/@types/notice.types.ts
  src/@types/user.types.ts
  src/api/getShopNotice.ts
  src/api/postApply.ts
  src/components/@common/GNBMenuButton/GNBMenuButton.tsx
  src/components/@common/GNBNav/GNBNav.module.css
  src/components/@common/GNBNav/GNBNav.tsx
  src/components/@common/Modal/NotificationModal/NotificationModal.module.css
  src/components/@common/Modal/NotificationModal/NotificationModal.tsx
  src/components/@common/Modal/Wrapper.module.css
  src/components/@common/Modal/Wrapper.tsx
  src/components/notice/NoticeCard/NoticeCard.tsx
  src/components/notice/NoticeCustomized/NoticeCustomized.tsx
  src/components/notice/NoticeInfo/NoticeDescription/NoticeDescription.module.css
  src/components/notice/NoticeInfo/NoticeDescription/NoticeDescription.tsx
  src/components/notice/NoticeInfo/NoticeInfo.module.css
  src/components/notice/NoticeInfo/NoticeInfo.tsx
  src/components/notice/NoticeList/NoticeList.tsx
  src/components/notice/NoticeRecentViewed/NoticeRecentViewed.module.css
  src/components/notice/NoticeRecentViewed/NoticeRecentViewed.tsx
  src/pages/index.tsx
  src/pages/notice/NoticeDetail.module.css
  src/pages/notice/index.tsx
  src/pages/profile/index.tsx
  src/pages/profile/registration.tsx
  src/pages/signin/index.tsx
  src/utils/formatWorkTime.ts
  src/utils/noticeRecentViewed.ts
Labels: 1일, 페이지

#124 address input 컴포넌트 삭제
  src/components/@common/Input/AddressInput.tsx
Labels: fix

#127 fix: 버그 수정
  src/components/@common/GNBMenuButton/GNBMenuButton.tsx
  src/components/@common/GNBNav/GNBNav.tsx
  src/hooks/useOwnerRegist.ts
  src/pages/index.tsx
  src/pages/notice/index.tsx
  src/pages/owner/index.tsx
  src/pages/profile/index.tsx
  src/pages/profile/registration.tsx
  src/pages/signin/profile/detail.tsx
  src/pages/signin/profile/index.tsx
  src/pages/signin/profile/profile.module.css
  src/pages/signin/profile/registration.tsx
Labels: fix

#126 가게 상세 페이지
  src/components/@common/Button/PrimaryButton.module.css
  src/components/@common/Input/EmailInput.tsx
  src/components/@common/Input/Input.module.css
  src/components/@common/Input/StoreImageInput.tsx
  src/components/myprofile/ApplyHistory.module.css
  src/hooks/useShopInfo.ts
  src/pages/owner/detail.module.css
  src/pages/owner/detail.tsx
  src/pages/owner/index.tsx
  src/pages/owner/registration.tsx
  src/pages/profile/index.tsx
  src/pages/signin/index.tsx
  src/pages/signin/signin.module.css
Labels: fix, 페이지

#132 feat: 내가 등록한 공고 구현
  src/components/@common/GNBMenuButton/GNBMenuButton.tsx
  src/components/@common/Input/StoreImageInput.tsx
  src/components/notice/HourlyPayBadge/HourlyPayBadge.tsx
  src/components/notice/NoticeCard/NoticeCard.tsx
  src/components/notice/NoticeList/NoticeList.module.css
  src/components/notice/NoticeList/NoticeList.tsx
  src/components/owner/OwnerNotices/OwnerNotices.module.css
  src/components/owner/OwnerNotices/OwnerNotices.tsx
  src/hooks/useShopInfo.ts
  src/pages/owner/detail.module.css
  src/pages/owner/detail.tsx
  src/pages/owner/postnotice.tsx
Labels: 컴포넌트
